services:
  server:
    build: .
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - session-data:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
   image: postgres:16
   restart: always
   volumes:
     - db-data:/var/lib/postgresql/data
   env_file: .env
   user: $POSTGRES_USER
   ports:
     - "5432:5432"
   healthcheck:
     test: [ "CMD", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5

  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    restart: always


volumes:
 db-data:
 session-data:


