"""init database

Revision ID: f450e2c77807
Revises: 
Create Date: 2025-05-06 23:49:19.000305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f450e2c77807'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blacklist_chat')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_blacklist_chat__chat_id'))
    )
    op.create_table('our_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_our_user')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_our_user__telegram_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('our_user')
    op.drop_table('blacklist_chat')
    # ### end Alembic commands ###
